### ISSUE TITLE
[FR] (feature request title)

### ISSUE THREAD

**Issue by FulvioSpelta** [LONGER3D/Marlin2.0-lgt#2]
Hi all,
is this firmware suitable for LK4 Pro/U30 Pro ?

If no, is there a development plan to support these printers ?

**Comment by LONGER3D** [comment]
Of course YES. We will upload a branch for LK4 Pro, But just support basic print(no touch screen) now.

**Comment by FulvioSpelta** [comment]
Thanks, waiting for  the branch. Available for beta testing.
If possibile pls share your development plan for a ful lk4 pro/u30 pro support.

**Comment by lowkeyjoe** [comment]
The README has been updated. Please check it out.
