### ISSUE TITLE
[FR] LK4PRO with BLTouch

### ISSUE THREAD

**Issue by Ajtak** [LONGER3D/Marlin2.0-lgt#7]
I'm trying build for LK4_PRO with BLTOUCH, but BLTOUCH not working in this firmware.. 
I have enabled it.

Can you create branch LK4PRO_BLTOUCH?
Thanks.

**Comment by freyjoe18** [comment]
No problem. Thanks for your contribution.

**Comment by LONGER3D** [comment]
https://github.com/LONGER3D/Marlin2.0-lgt/tree/LKxPro-bltouch-dualblower
LKxPro-bltouch-dualblower branch. please check it out
